"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {LockKeyhole,Loader2} from "lucide-react";
export default function ChangePassword(){
 const router=useRouter(),[ready,setReady]=useState(false),[p1,setP1]=useState(""),[p2,setP2]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}const {data}=await s.from("profiles").select("force_password_change").eq("id",user.id).single();if(!data?.force_password_change){router.replace("/dashboard");return}setReady(true)})()},[router]);
 async function save(e:FormEvent){e.preventDefault();setErr("");if(p1.length<8){setErr("Usá una contraseña de al menos 8 caracteres.");return}if(p1!==p2){setErr("Las contraseñas no coinciden.");return}setBusy(true);const s=createClient();const {data:{user}}=await s.auth.getUser();const {error}=await s.auth.updateUser({password:p1});if(error){setErr(error.message);setBusy(false);return}if(user)await s.from("profiles").update({force_password_change:false}).eq("id",user.id);router.replace("/dashboard");router.refresh()}
 if(!ready)return <main className="grid min-h-screen place-items-center bg-[#061f48] text-white">Verificando acceso...</main>;
 return <main className="grid min-h-screen place-items-center bg-[#061f48] p-4"><section className="w-full max-w-md rounded-3xl bg-white p-7 text-slate-900 shadow-2xl"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#08295c] font-black text-white">eQ</span><h1 className="mt-5 text-2xl font-black text-[#08295c]">Creá tu contraseña personal</h1><p className="mt-2 text-sm text-slate-500">Por seguridad debes crear una nueva contraseña antes de continuar.</p><form onSubmit={save} className="mt-6 space-y-4"><label className="block text-sm font-bold">Nueva contraseña<input type="password" required value={p1} onChange={e=>setP1(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">Confirmar nueva contraseña<input type="password" required value={p2} onChange={e=>setP2(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label>{err&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{err}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#08295c] p-3 font-black text-white">{busy?<Loader2 className="animate-spin" size={17}/>:<LockKeyhole size={17}/>}Guardar y continuar</button></form></section></main>
}