"use client";
import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";import {useRouter} from "next/navigation";
type T={id:string;ticket_number:string;subject:string;request_type:string;description:string;priority:string;status:string;created_at:string};
export default function Portal(){const sb=useMemo(()=>createClient(),[]),r=useRouter(),[client,setClient]=useState<any>(null),[tickets,setTickets]=useState<T[]>([]),[selected,setSelected]=useState<T|null>(null),[msgs,setMsgs]=useState<any[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(true),[reply,setReply]=useState("");
async function load(){const{data:{user}}=await sb.auth.getUser();if(!user){r.replace("/portal/login");return}const{data:m}=await sb.from("client_portal_users").select("client_id,full_name,active").eq("user_id",user.id).maybeSingle();if(!m?.active){r.replace("/portal/login");return}const[{data:c},{data:t}]=await Promise.all([sb.from("clients").select("id,name").eq("id",m.client_id).single(),sb.from("tickets").select("*").eq("client_id",m.client_id).order("created_at",{ascending:false})]);setClient({...c,person:m.full_name});setTickets(t||[]);setBusy(false)}
useEffect(()=>{load()},[]);
async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await sb.from("tickets").insert({client_id:client.id,subject:fd.get("subject"),request_type:fd.get("type"),description:fd.get("description"),priority:"normal",opened_by:null});if(error)alert(error.message);else{setOpen(false);await load()}}
async function view(t:T){setSelected(t);const{data}=await sb.from("ticket_messages").select("*").eq("ticket_id",t.id).eq("is_internal",false).order("created_at");setMsgs(data||[])}
async function send(e:React.FormEvent){e.preventDefault();if(!selected||!reply.trim())return;const{error}=await sb.from("ticket_messages").insert({ticket_id:selected.id,author_id:null,message:reply.trim(),is_internal:false});if(error)alert(error.message);else{setReply("");await view(selected)}}
async function out(){await sb.auth.signOut();r.replace("/portal/login")}
const sl:any={new:"Nuevo",review:"En revisión",in_progress:"En proceso",waiting_client:"Esperando tu respuesta",resolved:"Resuelto",closed:"Cerrado"};
if(busy)return <main className="min-h-screen bg-[#f4f9fc] grid place-items-center text-[#044474]">Cargando portal...</main>;
return <main className="min-h-screen bg-[#f4f9fc] text-[#044474]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div><b>eQuantum</b><span className="ml-3 text-sm text-slate-400">Portal del Cliente</span></div><button onClick={out} className="text-sm text-slate-500">Cerrar sesión</button></div></header><div className="mx-auto max-w-6xl p-5 md:p-8"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-widest text-[#08B2ED]">Soporte</p><h1 className="mt-1 text-3xl font-semibold">{client?.name}</h1><p className="mt-1 text-sm text-slate-500">Tus solicitudes y seguimiento con eQuantum.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-[#044474] px-5 py-3 text-sm font-medium text-white">+ Nuevo ticket</button></div><section className="overflow-hidden rounded-[22px] border border-slate-200 bg-white"><div className="grid grid-cols-[110px_1fr_120px] bg-slate-50 px-5 py-3 text-[10px] uppercase tracking-wider text-slate-400"><span>Ticket</span><span>Asunto</span><span>Estado</span></div>{tickets.length?tickets.map(t=><button key={t.id} onClick={()=>view(t)} className="grid w-full grid-cols-[110px_1fr_120px] items-center border-t border-slate-100 px-5 py-4 text-left hover:bg-[#f8fdff]"><b className="text-xs text-[#08B2ED]">{t.ticket_number}</b><div><p className="text-sm font-medium">{t.subject}</p><small className="text-slate-400">{new Date(t.created_at).toLocaleDateString("es-PY")}</small></div><span className="text-xs">{sl[t.status]||t.status}</span></button>):<p className="p-10 text-center text-sm text-slate-400">Todavía no tenés tickets.</p>}</section></div>
{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#044474]/35 p-4"><form onSubmit={create} className="w-full max-w-xl rounded-[24px] bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-semibold">Nuevo ticket</h2><button type="button" onClick={()=>setOpen(false)}>Cerrar</button></div><label className="block text-sm">Asunto<input required name="subject" className="mt-2 mb-4 w-full rounded-xl border p-3"/></label><label className="block text-sm">Tipo<select name="type" className="mt-2 mb-4 w-full rounded-xl border p-3"><option>Soporte técnico</option><option>Ecommerce</option><option>Desarrollo web</option><option>Marketing</option><option>Diseño</option><option>Consulta</option><option>Otro</option></select></label><label className="block text-sm">Describe el requerimiento<textarea required name="description" rows={5} className="mt-2 w-full rounded-xl border p-3"/></label><button className="mt-5 w-full rounded-xl bg-[#044474] py-3 text-white">Enviar solicitud</button></form></div>}
{selected&&<div className="fixed inset-0 z-50 flex justify-end bg-[#044474]/35"><div className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 md:p-8"><div className="flex justify-between gap-4"><div><b className="text-xs text-[#08B2ED]">{selected.ticket_number}</b><h2 className="mt-1 text-xl font-semibold">{selected.subject}</h2><p className="mt-1 text-xs text-slate-400">{sl[selected.status]}</p></div><button onClick={()=>setSelected(null)} className="self-start text-slate-500">Cerrar</button></div><div className="my-6 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{selected.description}</div><h3 className="mb-3 text-sm font-medium">Conversación</h3><div className="space-y-3">{msgs.map(m=><div key={m.id} className="rounded-xl border border-slate-100 bg-[#f8fbfd] p-4"><p className="text-sm whitespace-pre-wrap">{m.message}</p><small className="mt-2 block text-slate-400">{new Date(m.created_at).toLocaleString("es-PY")}</small></div>)}</div>{!["resolved","closed"].includes(selected.status)&&<form onSubmit={send} className="mt-6"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={4} placeholder="Escribí tu respuesta..." className="w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-[#08B2ED]"/><button disabled={!reply.trim()} className="mt-3 rounded-xl bg-[#044474] px-5 py-3 text-sm text-white disabled:opacity-50">Enviar respuesta</button></form>}</div></div>}</main>}