-- Servicios Activos + Proyectos + Tareas V2
-- PREPARACION. No ejecutar en produccion.
-- Regla: Sale, Active Service, Project, Task y Ticket tienen ciclos de vida independientes.

begin;

-- Una línea vendida puede originar un servicio operativo sin depender del Project.
alter table public.active_services
  add column if not exists sale_item_id uuid references public.sale_items(id) on delete set null;
alter table public.active_services
  add column if not exists owner_id uuid references public.profiles(id) on delete set null;
alter table public.active_services
  add column if not exists updated_at timestamptz not null default now();

-- Evita crear dos veces el mismo servicio desde una misma línea de venta.
create unique index if not exists active_services_sale_item_uq
  on public.active_services(sale_item_id)
  where sale_item_id is not null;

-- Project puede implementar un servicio activo. No todo servicio requiere Project.
alter table public.projects
  add column if not exists active_service_id uuid references public.active_services(id) on delete set null;

create index if not exists projects_active_service_idx
  on public.projects(active_service_id)
  where active_service_id is not null;

-- Task puede pertenecer al Project y/o relacionarse directamente con Active Service.
-- active_service_id ya fue preparado en model_data_v2_expand.
create index if not exists tasks_active_service_idx
  on public.tasks(active_service_id)
  where active_service_id is not null;

-- Contrato de integridad: Project cerrado no puede ocultar trabajo operativo pendiente.
-- Se prepara una función de validación SIN trigger automático de cierres cruzados.
create or replace function public.project_has_open_tasks(p_project_id uuid)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select exists (
    select 1 from public.tasks t
    where t.project_id = p_project_id
      and t.status::text not in ('completada','cancelada')
  );
$$;

-- Historial de ciclo de vida de servicio. No confundir con Audit Log.
create table if not exists public.active_service_events (
  id bigint generated by default as identity primary key,
  active_service_id uuid not null references public.active_services(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null default now(),
  reason text,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists active_service_events_service_idx
  on public.active_service_events(active_service_id,occurred_at desc);
alter table public.active_service_events enable row level security;

commit;

-- CONTRATO OPERATIVO V2
--
-- WON -> Sale:
-- * no crea Project automáticamente por el solo hecho de ganar.
-- * por cada sale_item que represente un servicio que deba operar, el backend
--   puede crear exactamente un Active Service usando sale_item_id UNIQUE.
--
-- Active Service -> Project:
-- * crear Project solo cuando la ejecución requiera un proyecto/implementación.
-- * un servicio recurrente puede existir sin Project.
-- * cerrar Project NO cambia active_services.status.
--
-- Project -> Task:
-- * Task ejecuta trabajo.
-- * Project no puede cerrarse silenciosamente si mantiene Tasks abiertas.
-- * completar/cancelar todas las Tasks NO cierra Project automáticamente.
--
-- Task -> Active Service:
-- * completar/cancelar Task NO termina Active Service.
--
-- Task -> Ticket:
-- * completar Task NO cierra Ticket.
-- * Ticket puede tener 0, 1 o N Tasks.
--
-- Active Service:
-- * finalizar/pausar requiere operación explícita + motivo/evento.
-- * finalizar servicio NO debe borrar Projects/Tasks/Tickets históricos.
