"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bell, CheckCircle2, Gauge, Lightbulb, LogOut, Menu, MessageSquare, Plus, Radar, Sparkles, Users, X, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

type View = "dashboard"|"tasks"|"triage"|"radar"|"bi"|"improvements"|"chat"|"users";
const nav:{id:View;label:string;icon:any}[]=[
  {id:"dashboard",label:"Inicio",icon:Gauge},{id:"tasks",label:"Tareas",icon:CheckCircle2},
  {id:"triage",label:"Triage de Tareas",icon:Zap},{id:"radar",label:"Radar de Seguimiento",icon:Radar},
  {id:"bi",label:"Business Intelligence",icon:BarChart3},{id:"improvements",label:"Mejoras IA",icon:Sparkles},
  {id:"chat",label:"Chat interno",icon:MessageSquare},{id:"users",label:"Usuarios y accesos",icon:Users},
];
type Task={id:string;title:string;area:string;task_type:string;priority:string;status:string;estimated_minutes:number|null;triage_score:number;created_at:string};
const priorityLabel:Record<string,string>={critical:"Crítica",high:"Alta",medium:"Media",normal:"Normal",low:"Baja"};
const statusLabel:Record<string,string>={pending:"Pendiente",in_progress:"En curso",paused:"Pausada",blocked:"Bloqueada",waiting_client:"Esperando cliente",completed:"Completada",cancelled:"Cancelada"};

export default function DashboardPage(){
 const router=useRouter(); const [view,setView]=useState<View>("dashboard"); const [menu,setMenu]=useState(false);
 const [messages,setMessages]=useState(["Daniel: Revisé el avance de Portal Verde.","Derlis: Perfecto, seguimos con checkout."]);
 const [tasks,setTasks]=useState<Task[]>([]); const [taskModal,setTaskModal]=useState(false); const [loadingTasks,setLoadingTasks]=useState(true);
 async function loadTasks(){setLoadingTasks(true);const s=createClient();const {data}=await s.from("tasks").select("id,title,area,task_type,priority,status,estimated_minutes,triage_score,created_at").order("created_at",{ascending:false});setTasks((data||[]) as Task[]);setLoadingTasks(false)}
 useEffect(()=>{loadTasks()},[]);
 async function createTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const urgency=Number(form.get("client_urgency")||1);const affects=form.get("affects_sales")==="on";const blocks=form.get("blocks_others")==="on";const strategic=form.get("strategic")==="on";const score=Math.min(100,25+(urgency*8)+(affects?15:0)+(blocks?15:0)+(strategic?10:0));const priority=score>=80?"critical":score>=65?"high":score>=50?"medium":score>=35?"normal":"low";const {error}=await s.from("tasks").insert({title:String(form.get("title")),area:String(form.get("area")),task_type:String(form.get("task_type")),assignee_id:user.id,created_by:user.id,due_date:form.get("due_date")||null,client_urgency:urgency,estimated_minutes:Number(form.get("estimated_minutes")||60),description:String(form.get("description")||""),affects_sales:affects,blocks_others:blocks,strategic,triage_score:score,priority,triage_reasons:[affects?"Impacta ventas":null,blocks?"Bloquea a otros":null,strategic?"Impacto estratégico":null].filter(Boolean)});if(error){alert("No se pudo guardar: "+error.message);return}setTaskModal(false);await loadTasks();}
 const active=tasks.filter(t=>!["completed","cancelled"].includes(t.status)); const critical=active.filter(t=>t.priority==="critical").length; const high=active.filter(t=>t.priority==="high").length; const completed=tasks.filter(t=>t.status==="completed").length; const cards=[["Tareas activas",String(active.length),"Carga vigente"],["Críticas",String(critical),"Atención inmediata"],["Altas",String(high),"Resolver después de críticas"],["Seguimientos","0","Radar requiere atención"],["Completadas",String(completed),"Ejecución registrada"]];
 const title=nav.find(n=>n.id===view)?.label||"Inicio";
 const today=useMemo(()=>new Date().toLocaleDateString("es-PY",{weekday:"long",day:"numeric",month:"long"}),[]);
 async function logout(){const s=createClient();await s.auth.signOut();router.replace("/login");router.refresh();}
 function go(v:View){setView(v);setMenu(false)}
 return <main className="min-h-screen bg-[#f2f6fb] text-[#14243b]">
  <aside className={`fixed inset-y-0 left-0 z-50 flex w-[258px] flex-col bg-gradient-to-b from-[#061f48] to-[#08295c] p-3 text-white transition-transform lg:translate-x-0 ${menu?"translate-x-0":"-translate-x-full"}`}>
   <div className="flex items-center gap-3 border-b border-white/10 px-2 py-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white font-black text-[#08295c]">eQ</span><div><b className="text-sm">Gestión Inteligente</b><span className="block text-[10px] text-blue-200/70">equipo.equantum.com.py</span></div><button onClick={()=>setMenu(false)} className="ml-auto lg:hidden"><X size={18}/></button></div>
   <nav className="mt-3 flex-1 space-y-1 overflow-y-auto">{nav.map(n=><button key={n.id} onClick={()=>go(n.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold ${view===n.id?"bg-[#1ca5e9]/20 text-white":"text-blue-50/80 hover:bg-white/5"}`}><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/10"><n.icon size={15}/></span>{n.label}</button>)}</nav>
   <div className="rounded-xl bg-white/10 p-3"><b className="block text-xs">Derlis Aguilera</b><span className="text-[11px] text-blue-100/60">Administrador global</span></div>
   <button onClick={logout} className="mt-2 flex items-center justify-center gap-2 rounded-xl border border-white/20 py-2.5 text-sm font-bold"><LogOut size={15}/>Cerrar sesión</button>
  </aside>
  {menu&&<button onClick={()=>setMenu(false)} className="fixed inset-0 z-40 bg-black/40 lg:hidden"/>}
  <div className="lg:pl-[258px]">
   <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-[#dfe7f1] bg-white px-4 lg:px-6"><div className="flex items-center gap-3"><button onClick={()=>setMenu(true)} className="rounded-lg bg-slate-100 p-2 lg:hidden"><Menu size={19}/></button><div><h2 className="font-black text-[#08295c]">{title}</h2><small className="text-slate-400">{today}</small></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-[#eef7ff] px-3 py-2 text-[11px] font-black text-[#08295c] sm:inline">● Sistema operativo</span><span className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-[#0ba9e8] to-[#08295c] text-xs font-black text-white">DA</span></div></header>
   <div className="mx-auto max-w-[1440px] p-4 lg:p-6">
    {view==="dashboard"&&<Dashboard cards={cards} tasks={tasks} onNew={()=>setTaskModal(true)}/>}
    {view==="tasks"&&<Tasks tasks={tasks} loading={loadingTasks} onNew={()=>setTaskModal(true)}/>}
    {view==="triage"&&<Triage tasks={tasks}/>}
    {view==="radar"&&<RadarView/>}
    {view==="bi"&&<BI/>}
    {view==="improvements"&&<Improvements/>}
    {view==="chat"&&<Chat messages={messages} setMessages={setMessages}/>}
    {view==="users"&&<UsersView/>}
   </div>
  </div>
  {taskModal&&<TaskModal onClose={()=>setTaskModal(false)} onSubmit={createTask}/>} 
<style jsx global>{` .inputV3{width:100%;border:1px solid #dbe4ee;border-radius:12px;padding:10px 12px;background:#fff;color:#14243b;outline:none}.inputV3:focus{border-color:#0ba9e8;box-shadow:0 0 0 3px rgba(11,169,232,.10)} `}</style>
 </main>
}
function Head({eyebrow,title,sub,action,onAction}:{eyebrow:string,title:string,sub:string,action?:string,onAction?:()=>void}){return <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-[#0ba9e8]">{eyebrow}</p><h1 className="mt-1 text-2xl font-black text-[#08295c] lg:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{sub}</p></div>{action&&<button onClick={onAction} className="w-fit rounded-xl bg-[#08295c] px-4 py-3 text-sm font-black text-white"><Plus className="mr-1 inline" size={15}/>{action}</button>}</div>}
function Dashboard({cards,tasks,onNew}:{cards:string[][];tasks:Task[];onNew:()=>void}){const ordered=[...tasks].filter(t=>!["completed","cancelled"].includes(t.status)).sort((a,b)=>b.triage_score-a.triage_score);return <><Head eyebrow="Centro de control" title="Buenos días, Derlis" sub="Tu jornada, prioridades y lectura empresarial en un solo lugar." action="Nueva tarea" onAction={onNew}/><section className="rounded-[20px] bg-gradient-to-r from-[#083873] to-[#0d5799] p-5 text-white"><p className="text-[11px] font-black uppercase tracking-[.15em] text-cyan-200">Inteligencia del día</p><h2 className="mt-2 text-xl font-black">Resumen ejecutivo de la jornada</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{[["HECHOS",tasks.length?("Hay "+ordered.length+" tareas activas registradas."):"Todavía no hay tareas registradas."],["LECTURA",ordered[0]?("La prioridad actual es: "+ordered[0].title+"."):"Cargá la primera tarea para comenzar el análisis."],["SUGERENCIA","Registrar urgencia, impacto y tiempo estimado mejora el Triage y el BI." ]].map(x=><div key={x[0]} className="rounded-xl border border-white/15 bg-white/10 p-4"><b className="text-[11px] text-cyan-100">{x[0]}</b><p className="mt-2 text-sm leading-5">{x[1]}</p></div>)}</div></section><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map(c=><div key={c[0]} className="rounded-2xl border border-[#dfe7f1] bg-white p-4"><span className="text-[11px] font-bold text-slate-500">{c[0]}</span><b className="mt-2 block text-3xl text-[#08295c]">{c[1]}</b><small className="text-slate-400">{c[2]}</small></div>)}</div><div className="mt-4"><Panel title="Prioridades de hoy · Triage">{ordered.length?ordered.slice(0,5).map((t,i)=><Row key={t.id} n={i+1} title={t.title} sub={t.area+" · Score "+t.triage_score} tag={priorityLabel[t.priority]||t.priority}/>):<Empty text="Todavía no hay tareas. Creá la primera para activar el Triage."/ >}</Panel></div></>}
function Tasks({tasks,loading,onNew}:{tasks:Task[];loading:boolean;onNew:()=>void}){return <><Head eyebrow="Operación" title="Tareas" sub="Trabajo real registrado en Supabase." action="Nueva tarea" onAction={onNew}/><Panel title="Todas las tareas">{loading?<Empty text="Cargando tareas..."/>:tasks.length?tasks.map((t,i)=><Row key={t.id} n={i+1} title={t.title} sub={t.area+" · "+t.task_type+" · "+(t.estimated_minutes||0)+" min"} tag={statusLabel[t.status]||t.status}/>):<Empty text="No hay tareas registradas todavía."/ >}</Panel></>}
function Triage({tasks}:{tasks:Task[]}){const ordered=[...tasks].filter(t=>!["completed","cancelled"].includes(t.status)).sort((a,b)=>b.triage_score-a.triage_score);return <><Head eyebrow="Prioridad inteligente" title="Triage de Tareas" sub="Orden real según el puntaje registrado."/><div className="grid gap-3">{ordered.length?ordered.map((t,i)=><div key={t.id} className="rounded-2xl border bg-white p-4"><div className="flex gap-4"><b className="text-2xl text-[#0ba9e8]">{String(i+1).padStart(2,"0")}</b><div className="flex-1"><h3 className="font-black text-[#08295c]">{t.title}</h3><p className="text-sm text-slate-500">{t.area} · Score {t.triage_score}/100</p></div><span className="h-fit rounded-full bg-orange-50 px-3 py-1 text-xs font-black text-orange-700">{priorityLabel[t.priority]||t.priority}</span></div></div>):<Empty text="El Triage se activará cuando registres tareas."/ >}</div></>}
function TaskModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="fixed inset-0 z-[80] grid place-items-center bg-[#04152b]/60 p-4"><form onSubmit={onSubmit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#0ba9e8]">Operación</p><h2 className="text-2xl font-black text-[#08295c]">Nueva tarea</h2></div><button type="button" onClick={onClose} className="rounded-lg bg-slate-100 p-2"><X size={18}/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Título *"><input name="title" required className="inputV3" placeholder="Ej. Preparar propuesta comercial"/></Field><Field label="Área *"><select name="area" required className="inputV3"><option>Ecommerce</option><option>Desarrollo</option><option>Marketing</option><option>Diseño</option><option>Comercial</option><option>Administración</option><option>Soporte</option></select></Field><Field label="Tipo de tarea *"><select name="task_type" className="inputV3"><option>Operativa</option><option>Cliente</option><option>Comercial</option><option>Desarrollo</option><option>Seguimiento</option><option>Interna</option></select></Field><Field label="Fecha límite"><input name="due_date" type="date" className="inputV3"/></Field><Field label="Urgencia del cliente"><select name="client_urgency" className="inputV3"><option value="1">1 · Baja</option><option value="2">2</option><option value="3">3 · Media</option><option value="4">4</option><option value="5">5 · Urgente</option></select></Field><Field label="Tiempo estimado (min)"><input name="estimated_minutes" type="number" min="5" defaultValue="60" className="inputV3"/></Field></div><Field label="Descripción"><textarea name="description" rows={3} className="inputV3 mt-1" placeholder="Contexto necesario para ejecutar la tarea"/></Field><div className="mt-4 grid gap-2 sm:grid-cols-3">{[["affects_sales","Afecta ventas"],["blocks_others","Bloquea a otros"],["strategic","Es estratégica"]].map(x=><label key={x[0]} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" name={x[0]}/>{x[1]}</label>)}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-3 text-sm font-bold">Cancelar</button><button type="submit" className="rounded-xl bg-[#08295c] px-5 py-3 text-sm font-black text-white">Guardar tarea</button></div></form></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-bold text-slate-600">{label}<div className="mt-1">{children}</div></label>}
function Empty({text}:{text:string}){return <div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">{text}</div>}
function RadarView(){return <><Head eyebrow="Continuidad" title="Radar de Seguimiento" sub="Asuntos que no pueden quedar olvidados."/><section className="rounded-[20px] bg-[#08295c] p-5 text-white"><h2 className="text-xl font-black">3 asuntos requieren seguimiento</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{[["VENCIDOS","1 seguimiento superó su fecha prevista."],["SILENCIOS","2 asuntos llevan varios días sin movimiento."],["PRÓXIMA ACCIÓN","Atender primero vencidos y silencios largos."]].map(x=><div key={x[0]} className="rounded-xl bg-white/10 p-4"><b className="text-xs text-cyan-200">{x[0]}</b><p className="mt-2 text-sm">{x[1]}</p></div>)}</div></section></>}
function BI(){return <><Head eyebrow="Business Intelligence" title="Lectura empresarial" sub="Qué nos está diciendo el trabajo acumulado."/><div className="grid gap-4 md:grid-cols-3">{[["DEMANDA","Soporte y ecommerce concentran la mayor carga."],["CAPACIDAD","8 horas estimadas permanecen abiertas."],["CLIENTES","Portal Verde concentra la prioridad operativa actual."]].map(x=><Panel key={x[0]} title={x[0]}><p className="text-sm leading-6 text-slate-600">{x[1]}</p></Panel>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Carga por tipo"><Bars/></Panel><Panel title="Lecturas"><p className="text-sm leading-7 text-slate-600">La base histórica irá mejorando a medida que el equipo registre tareas, tiempos, clientes y seguimientos de forma consistente.</p></Panel></div></>}
function Improvements(){return <><Head eyebrow="Calidad de información" title="Mejoras IA" sub="Sugerencias que siempre requieren aprobación humana."/><div className="grid gap-3 md:grid-cols-2">{["Mejorar títulos poco descriptivos","Detectar tareas múltiples","Crear seguimientos faltantes","Recuperar silencios operativos"].map((x,i)=><Panel key={x} title={x}><p className="text-sm text-slate-500">Sugerencia #{i+1}. Revisar y aplicar solo si aporta claridad al equipo.</p><div className="mt-4 flex gap-2"><button className="rounded-lg bg-[#08295c] px-3 py-2 text-xs font-bold text-white">Aceptar</button><button className="rounded-lg border px-3 py-2 text-xs font-bold">Rechazar</button></div></Panel>)}</div></>}
function Chat({messages,setMessages}:{messages:string[],setMessages:(x:string[])=>void}){const [v,setV]=useState("");return <><Head eyebrow="Equipo" title="Chat interno" sub="Conversaciones operativas en un solo lugar."/><Panel title="# general"><div className="min-h-[320px] space-y-2">{messages.map(m=><div key={m} className="rounded-xl bg-[#f4f7fb] p-3 text-sm">{m}</div>)}</div><div className="mt-3 flex gap-2"><input value={v} onChange={e=>setV(e.target.value)} className="min-w-0 flex-1 rounded-xl border px-3 py-2" placeholder="Escribir mensaje..."/><button onClick={()=>{if(v.trim()){setMessages([...messages,"Derlis: "+v]);setV("")}}} className="rounded-xl bg-[#08295c] px-4 text-sm font-bold text-white">Enviar</button></div></Panel></>}
function UsersView(){return <><Head eyebrow="Gerencia" title="Usuarios y accesos" sub="Control de miembros, roles y permisos." action="Nuevo usuario"/><div className="grid gap-3 md:grid-cols-3">{[["Derlis Aguilera","Administrador global"],["Daniel Sosa","Operaciones"],["Equipo eQuantum","Colaborador"]].map(x=><Panel key={x[0]} title={x[0]}><p className="text-sm text-slate-500">{x[1]}</p><span className="mt-3 inline-block rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Activo</span></Panel>)}</div></>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="rounded-2xl border border-[#dfe7f1] bg-white p-4 shadow-[0_5px_20px_rgba(20,50,85,.04)]"><h2 className="mb-3 font-black text-[#08295c]">{title}</h2>{children}</section>}
function Row({n,title,sub,tag}:{n:number,title:string,sub:string,tag:string}){return <div className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#eef7ff] text-xs font-black text-[#0b76b7]">{n}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{title}</p><p className="truncate text-xs text-slate-400">{sub}</p></div><span className="hidden rounded-full bg-[#eef7ff] px-2 py-1 text-[10px] font-black text-[#08295c] sm:block">{tag}</span></div>}
function Bars(){return <div className="flex h-44 items-end gap-4">{[75,55,42,30,22].map((h,i)=><div key={i} className="flex flex-1 flex-col items-center justify-end gap-2"><b className="text-xs text-[#08295c]">{h}</b><div className="w-full max-w-12 rounded-t-lg bg-[#0ba9e8]" style={{height:h+"%"}}/><small className="text-[9px] text-slate-400">{["Soporte","Web","Shopify","SEO","CRM"][i]}</small></div>)}</div>}
